version: "3.8"

services:
  postgres:
    image: 'postgres:9.6.6'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: langxpay_dev
    ports:
      - "5432:5432"